services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: bash -c "bin/rails db:create && bin/rails db:migrate && bin/rails db:schema:load && bin/rails db:seed && rm -f tmp/pids/server.pid && bin/dev"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  internal-api:
    image: nginx:latest
    volumes:
      - ./internal-api:/usr/share/nginx/html:ro

volumes:
  postgres-data:
